"""
Grounded credit card benefit data.
This is the source of truth injected into the Gemini agent — no hallucinations.
"""

CARD_DATABASE = {
    "amex_gold": {
        "id": "amex_gold",
        "name": "American Express Gold Card",
        "network": "Amex",
        "annual_fee": 250,
        "color": "#B8860B",
        "earning_rates": {
            "dining": 4,
            "groceries": 4,
            "flights_direct": 3,
            "other": 1,
        },
        "credits": [
            {
                "id": "dining_credit",
                "name": "Dining Credit",
                "amount": 10,
                "frequency": "monthly",
                "annual_value": 120,
                "merchants": ["Grubhub", "Seamless", "The Cheesecake Factory", "Goldbelly", "Wine.com", "Five Guys"],
                "description": "$10/month at select dining partners",
                "expires": "end_of_month",
                "how_to_use": "Pay with your Amex Gold at any eligible merchant. The statement credit posts automatically — no enrollment needed. Check Grubhub and Five Guys first since they're easiest to use.",
                "link": "https://www.americanexpress.com/us/credit-cards/features-benefits/products/gold-card/dining-credit/",
                "link_label": "View eligible restaurants",
                "auto_detected": True,
                "tip": "Grubhub lets you order from thousands of restaurants — use it to effectively get $10 off any delivery order every month.",
            },
            {
                "id": "uber_cash",
                "name": "Uber Cash",
                "amount": 10,
                "frequency": "monthly",
                "annual_value": 120,
                "merchants": ["Uber", "Uber Eats"],
                "description": "$10/month Uber Cash for rides or Uber Eats",
                "expires": "end_of_month",
                "how_to_use": "Add your Amex Gold to the Uber app as a payment method. Uber Cash loads automatically each month. It can be used for rides or Uber Eats orders. Unused Uber Cash does NOT roll over.",
                "link": "https://www.uber.com/us/en/u/amex-gold/",
                "link_label": "Set up in Uber app",
                "auto_detected": True,
                "tip": "Even if you don't use Uber rides, order $10 on Uber Eats at the end of every month to capture the full value.",
            },
            {
                "id": "hotel_collection",
                "name": "Hotel Collection Credit",
                "amount": 100,
                "frequency": "per_stay",
                "annual_value": 100,
                "merchants": ["Amex Hotel Collection properties"],
                "description": "$100 experience credit per eligible stay (2+ nights)",
                "expires": "annual",
                "how_to_use": "Book through AmexTravel.com and select a 'Hotel Collection' property. Requires a minimum 2-night stay. The $100 credit is applied as an experience credit at the property (dining, spa, resort activities).",
                "link": "https://www.amextravel.com/hotel_programs/hotel_collection",
                "link_label": "Browse Hotel Collection",
                "auto_detected": False,
                "tip": "The credit applies to on-property charges, not the room rate. Plan to dine at the hotel restaurant or book a spa treatment.",
            },
            {
                "id": "resy_credit",
                "name": "Resy Dining Credit",
                "amount": 50,
                "frequency": "semi_annual",
                "annual_value": 100,
                "merchants": ["Resy"],
                "description": "$50 per half-year toward dining at Resy restaurants",
                "expires": "semi_annual",
                "how_to_use": "Book a restaurant through the Resy app or website and pay with your Amex Gold card. The credit applies automatically. $50 available Jan–Jun, $50 available Jul–Dec.",
                "link": "https://resy.com/",
                "link_label": "Browse Resy restaurants",
                "auto_detected": True,
                "tip": "Resy lists thousands of top restaurants in major cities. Use it for date nights or special dinners — the credit stacks with the 4x dining points.",
            },
        ],
        "total_annual_credits": 440,
        "net_value_after_fee": 90,
        "best_for": ["foodies", "grocery shoppers", "Uber users"],
        "transfer_partners": ["Delta SkyMiles", "Marriott Bonvoy", "Hilton Honors", "British Airways"],
    },
    "amex_platinum": {
        "id": "amex_platinum",
        "name": "American Express Platinum Card",
        "network": "Amex",
        "annual_fee": 695,
        "color": "#A8A9AD",
        "earning_rates": {
            "flights_direct": 5,
            "flights_amex_travel": 5,
            "hotels_amex_travel": 5,
            "other": 1,
        },
        "credits": [
            {
                "id": "airline_fee",
                "name": "Airline Fee Credit",
                "amount": 200,
                "frequency": "annual",
                "annual_value": 200,
                "merchants": ["Select airline for incidental fees"],
                "description": "$200 airline fee credit for checked bags, seat upgrades, in-flight purchases",
                "expires": "annual",
                "how_to_use": "First, enroll a preferred airline at americanexpress.com/airlinechoice. Then use your Platinum card for incidental fees (checked bags, seat selection, in-flight food/Wi-Fi) on that airline. The credit posts automatically within a few days.",
                "link": "https://www.americanexpress.com/en-us/benefits/travel/airline-fee-credit/",
                "link_label": "Select your airline",
                "auto_detected": False,
                "tip": "Many cardholders buy airline gift cards (e.g. Delta $200 e-gift card) to effectively turn this into a $200 flight discount on any ticket.",
            },
            {
                "id": "hotel_credit",
                "name": "Fine Hotels + Resorts Credit",
                "amount": 200,
                "frequency": "annual",
                "annual_value": 200,
                "merchants": ["Amex Fine Hotels + Resorts"],
                "description": "$200 hotel credit for prepaid bookings through Amex Travel",
                "expires": "annual",
                "how_to_use": "Book through AmexTravel.com and select a 'Fine Hotels + Resorts' property. Requires prepayment. The $200 credit is applied as a credit at the property for dining, spa, or room upgrades. You also get daily breakfast for two and guaranteed 4pm late checkout.",
                "link": "https://www.amextravel.com/hotel_programs/fine_hotels_and_resorts",
                "link_label": "Browse Fine Hotels + Resorts",
                "auto_detected": False,
                "tip": "FHR properties often include $100 in property credits on top of the card's $200 — making the effective benefit up to $300 on a single stay.",
            },
            {
                "id": "uber_cash_platinum",
                "name": "Uber Cash",
                "amount": 15,
                "frequency": "monthly",
                "annual_value": 189,
                "merchants": ["Uber", "Uber Eats"],
                "description": "$15/month Uber Cash ($35 in December)",
                "expires": "end_of_month",
                "how_to_use": "Add your Amex Platinum as a payment method in the Uber app. Uber Cash loads automatically each month. Works for both Uber rides and Uber Eats orders. December gets a bonus $35 total.",
                "link": "https://www.uber.com/us/en/u/amex-platinum/",
                "link_label": "Set up in Uber app",
                "auto_detected": True,
                "tip": "Stack with Uber Eats+ for additional savings. If you hold both Amex Gold and Platinum, each adds Uber Cash separately — up to $25/month combined.",
            },
            {
                "id": "digital_entertainment",
                "name": "Digital Entertainment Credit",
                "amount": 20,
                "frequency": "monthly",
                "annual_value": 240,
                "merchants": ["Disney+", "Hulu", "ESPN+", "Peacock", "NYT", "The Atlantic", "SiriusXM"],
                "description": "$20/month for select streaming and digital subscriptions",
                "expires": "end_of_month",
                "how_to_use": "Simply pay for any eligible subscription with your Amex Platinum. Statement credit posts automatically. No enrollment needed. You can combine multiple subscriptions to reach the $20 — e.g. Disney+ ($13.99) + Peacock ($5.99).",
                "link": "https://www.americanexpress.com/en-us/benefits/entertainment/digital-entertainment-credit/",
                "link_label": "View eligible subscriptions",
                "auto_detected": True,
                "tip": "Disney Bundle (Disney+, Hulu, ESPN+) at $19.99/month is almost entirely covered by this credit, leaving only $0 effectively.",
            },
            {
                "id": "walmart_plus",
                "name": "Walmart+ Credit",
                "amount": 12.95,
                "frequency": "monthly",
                "annual_value": 155,
                "merchants": ["Walmart+"],
                "description": "Monthly Walmart+ membership reimbursement",
                "expires": "end_of_month",
                "how_to_use": "Enroll in Walmart+ and pay the monthly membership fee ($12.95/month) with your Amex Platinum. Credit posts automatically. Walmart+ includes free shipping, fuel discounts, and Paramount+ streaming.",
                "link": "https://www.walmart.com/plus",
                "link_label": "Join Walmart+",
                "auto_detected": True,
                "tip": "Walmart+ includes a Paramount+ Essential subscription ($6/month value) at no extra cost, making the effective benefit even higher.",
            },
            {
                "id": "saks",
                "name": "Saks Fifth Avenue Credit",
                "amount": 50,
                "frequency": "semi_annual",
                "annual_value": 100,
                "merchants": ["Saks Fifth Avenue"],
                "description": "$50 credit Jan-Jun, $50 credit Jul-Dec",
                "expires": "semi_annual",
                "how_to_use": "Shop at Saks Fifth Avenue (in-store or online at saks.com) and pay with your Amex Platinum. Credit applies automatically: $50 Jan 1–Jun 30, another $50 Jul 1–Dec 31. No minimum purchase required.",
                "link": "https://www.saksfifthavenue.com/",
                "link_label": "Shop Saks Fifth Avenue",
                "auto_detected": False,
                "tip": "Saks often has beauty and fragrance items under $50 — a great way to get full value without overspending on luxury goods.",
            },
            {
                "id": "global_entry",
                "name": "Global Entry / TSA PreCheck Credit",
                "amount": 100,
                "frequency": "every_4_years",
                "annual_value": 25,
                "merchants": ["CBP", "TSA"],
                "description": "$100 Global Entry or $85 TSA PreCheck fee credit",
                "expires": "every_4_years",
                "how_to_use": "Apply for Global Entry at cbp.gov (or TSA PreCheck at tsa.gov). When you pay the application fee with your Amex Platinum, the credit posts automatically. Global Entry includes TSA PreCheck membership.",
                "link": "https://ttp.cbp.dhs.gov/",
                "link_label": "Apply for Global Entry",
                "auto_detected": False,
                "tip": "Always choose Global Entry over TSA PreCheck alone — it includes PreCheck, plus expedited customs when returning from international travel.",
            },
        ],
        "total_annual_credits": 1409,
        "net_value_after_fee": 714,
        "perks": ["Centurion Lounge access", "Priority Pass Select", "Delta SkyClub access (with Delta ticket)", "Fine Hotels + Resorts", "Global Entry"],
        "best_for": ["frequent flyers", "luxury travelers", "streaming subscribers"],
        "transfer_partners": ["Delta SkyMiles", "British Airways", "Air France/KLM", "Singapore Airlines", "Marriott Bonvoy"],
    },
    "chase_sapphire_reserve": {
        "id": "chase_sapphire_reserve",
        "name": "Chase Sapphire Reserve",
        "network": "Visa",
        "annual_fee": 550,
        "color": "#1a1a2e",
        "earning_rates": {
            "travel_chase_portal": 10,
            "hotels_chase_portal": 10,
            "dining": 3,
            "travel_other": 3,
            "other": 1,
        },
        "credits": [
            {
                "id": "travel_credit",
                "name": "Annual Travel Credit",
                "amount": 300,
                "frequency": "annual",
                "annual_value": 300,
                "merchants": ["Any travel purchase — airlines, hotels, Uber, Lyft, parking, tolls"],
                "description": "$300 travel credit — automatically applied to any travel purchase",
                "expires": "annual",
                "how_to_use": "Simply use your Chase Sapphire Reserve for any travel purchase. The credit applies automatically to the first $300 in travel charges each cardmember year — no enrollment needed. Qualifying purchases include airlines, hotels, motels, timeshares, campgrounds, car rentals, cruise lines, travel agencies, Uber, Lyft, parking, and tolls.",
                "link": "https://creditcards.chase.com/sapphire-credit-cards/sapphire-reserve",
                "link_label": "View card details",
                "auto_detected": True,
                "tip": "The travel credit resets each cardmember year (not calendar year). Use it first on Uber or Lyft rides if you haven't traveled yet — those count too.",
            },
            {
                "id": "global_entry_csr",
                "name": "Global Entry / TSA PreCheck Credit",
                "amount": 100,
                "frequency": "every_4_years",
                "annual_value": 25,
                "merchants": ["CBP", "TSA"],
                "description": "$100 Global Entry or $85 TSA PreCheck fee credit",
                "expires": "every_4_years",
            },
            {
                "id": "doordash_csr",
                "name": "DashPass + DoorDash Credit",
                "amount": 5,
                "frequency": "monthly",
                "annual_value": 60,
                "merchants": ["DoorDash"],
                "description": "$5/month DoorDash credit + complimentary DashPass",
                "expires": "end_of_month",
            },
        ],
        "total_annual_credits": 385,
        "net_value_after_fee": -165,
        "perks": ["Priority Pass lounge access", "1.5x point value in Chase Travel portal", "Trip delay/cancellation insurance", "Primary car rental insurance"],
        "best_for": ["frequent travelers", "diners", "Chase ecosystem users"],
        "transfer_partners": ["United MileagePlus", "Southwest", "British Airways", "Hyatt", "Marriott", "IHG"],
    },
    "chase_sapphire_preferred": {
        "id": "chase_sapphire_preferred",
        "name": "Chase Sapphire Preferred",
        "network": "Visa",
        "annual_fee": 95,
        "color": "#1a3a6e",
        "earning_rates": {
            "dining": 3,
            "travel": 2,
            "streaming": 2,
            "groceries_online": 3,
            "other": 1,
        },
        "credits": [
            {
                "id": "hotel_credit_csp",
                "name": "Annual Hotel Credit",
                "amount": 50,
                "frequency": "annual",
                "annual_value": 50,
                "merchants": ["Hotels booked through Chase Travel portal"],
                "description": "$50 annual hotel credit for Chase Travel bookings",
                "expires": "annual",
            },
        ],
        "total_annual_credits": 50,
        "net_value_after_fee": -45,
        "perks": ["1.25x point value in Chase portal", "Trip delay insurance", "Primary car rental insurance"],
        "best_for": ["beginner travel hackers", "occasional travelers", "Chase ecosystem entry point"],
        "transfer_partners": ["United MileagePlus", "Southwest", "British Airways", "Hyatt", "Marriott"],
    },
    "venture_x": {
        "id": "venture_x",
        "name": "Capital One Venture X",
        "network": "Visa",
        "annual_fee": 395,
        "color": "#8B0000",
        "earning_rates": {
            "travel_capital_one": 10,
            "hotels_capital_one": 5,
            "flights_capital_one": 5,
            "other": 2,
        },
        "credits": [
            {
                "id": "travel_credit_vx",
                "name": "Annual Travel Credit",
                "amount": 300,
                "frequency": "annual",
                "annual_value": 300,
                "merchants": ["Capital One Travel bookings only"],
                "description": "$300 credit for Capital One Travel portal bookings",
                "expires": "annual",
            },
            {
                "id": "anniversary_miles",
                "name": "Anniversary Miles Bonus",
                "amount": 10000,
                "frequency": "annual",
                "annual_value": 100,
                "merchants": ["Capital One Miles"],
                "description": "10,000 bonus miles every card anniversary (~$100 value)",
                "expires": "annual",
            },
            {
                "id": "global_entry_vx",
                "name": "Global Entry / TSA PreCheck Credit",
                "amount": 100,
                "frequency": "every_4_years",
                "annual_value": 25,
                "merchants": ["CBP", "TSA"],
                "description": "$100 Global Entry or $85 TSA PreCheck credit",
                "expires": "every_4_years",
            },
        ],
        "total_annual_credits": 425,
        "net_value_after_fee": 30,
        "perks": ["Priority Pass lounge access (unlimited)", "Capital One Lounge access", "2x miles on all purchases (baseline)"],
        "best_for": ["simplicity seekers", "lounge lovers", "flat-rate rewards maximizers"],
        "transfer_partners": ["Air Canada Aeroplan", "Turkish Airlines", "Singapore Airlines", "Avianca", "Choice Hotels"],
    },
    "citi_strata_premier": {
        "id": "citi_strata_premier",
        "name": "Citi Strata Premier Card",
        "network": "Mastercard",
        "annual_fee": 95,
        "color": "#00539B",
        "earning_rates": {
            "hotels": 3,
            "airlines": 3,
            "dining": 3,
            "groceries": 3,
            "gas": 3,
            "other": 1,
        },
        "credits": [
            {
                "id": "hotel_savings_citi",
                "name": "Annual Hotel Savings",
                "amount": 100,
                "frequency": "annual",
                "annual_value": 100,
                "merchants": ["Hotels booked through CitiTravel.com"],
                "description": "$100 off single hotel stay of $500+ per year",
                "expires": "annual",
            },
        ],
        "total_annual_credits": 100,
        "net_value_after_fee": 5,
        "perks": ["No foreign transaction fees", "Broad 3x category coverage"],
        "best_for": ["everyday spenders", "budget-conscious travelers", "grocery + gas households"],
        "transfer_partners": ["Turkish Airlines", "Air France/KLM", "Avianca", "Singapore Airlines", "Virgin Atlantic"],
    },

    # ── NO ANNUAL FEE CARDS ──────────────────────────────────────────────────
    "chase_freedom_unlimited": {
        "id": "chase_freedom_unlimited",
        "name": "Chase Freedom Unlimited",
        "network": "Visa",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#1a3a6e",
        "earning_rates": {
            "dining": 3,
            "drugstore": 3,
            "travel_chase_portal": 5,
            "other": 1.5,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "1.5% on everything, 3% dining & drugstores",
        "best_for": ["everyday spending", "dining", "Chase ecosystem pairing"],
        "transfer_partners": [],
        "perks": ["No annual fee", "Purchase protection", "Trip cancellation insurance", "0% intro APR 15 months"],
    },
    "citi_double_cash": {
        "id": "citi_double_cash",
        "name": "Citi Double Cash Card",
        "network": "Mastercard",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#00539B",
        "earning_rates": {
            "other": 2,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "2% on everything (1% when you buy + 1% when you pay)",
        "best_for": ["simplicity", "flat-rate cashback", "everything purchases"],
        "transfer_partners": ["Turkish Airlines", "Air France/KLM"],
        "perks": ["No annual fee", "No category tracking needed", "Balance transfer option"],
    },
    "capital_one_savorone": {
        "id": "capital_one_savorone",
        "name": "Capital One SavorOne",
        "network": "Mastercard",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#6B2D8B",
        "earning_rates": {
            "dining": 3,
            "groceries": 3,
            "entertainment": 3,
            "streaming": 3,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "3% on dining, groceries, entertainment & streaming",
        "best_for": ["foodies", "entertainment lovers", "grocery spenders"],
        "transfer_partners": [],
        "perks": ["No annual fee", "No foreign transaction fees", "3% on popular categories"],
    },
    "wells_fargo_active_cash": {
        "id": "wells_fargo_active_cash",
        "name": "Wells Fargo Active Cash",
        "network": "Visa",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#CC0000",
        "earning_rates": {
            "other": 2,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "2% cash rewards on all purchases",
        "best_for": ["simplicity", "flat-rate cashback", "no-fuss rewards"],
        "transfer_partners": [],
        "perks": ["No annual fee", "$200 welcome bonus", "Cellphone protection", "0% intro APR 15 months"],
    },
    "discover_it_cash_back": {
        "id": "discover_it_cash_back",
        "name": "Discover it Cash Back",
        "network": "Discover",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#FF6600",
        "earning_rates": {
            "rotating_quarterly": 5,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "5% on rotating quarterly categories (up to $1,500/qtr), 1% everything else",
        "best_for": ["category maximizers", "first-year bonus hunters", "flexible spenders"],
        "transfer_partners": [],
        "perks": ["No annual fee", "Cashback Match first year (doubles all cashback)", "No foreign transaction fees"],
    },
    "wells_fargo_autograph": {
        "id": "wells_fargo_autograph",
        "name": "Wells Fargo Autograph Card",
        "network": "Visa",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#CC0000",
        "earning_rates": {
            "travel": 3,
            "transit": 3,
            "gas": 3,
            "dining": 3,
            "streaming": 3,
            "phone": 3,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "3x points on travel, transit, gas, dining, streaming & phone plans — no annual fee",
        "best_for": ["transit commuters", "subway riders", "frequent diners", "no-annual-fee seekers"],
        "transfer_partners": [],
        "perks": [
            "No annual fee",
            "3x on transit (subway, buses, rideshare, ferries, tolls, parking)",
            "3x on travel (hotels, airlines, car rentals)",
            "3x on dining",
            "3x on gas & EV charging",
            "3x on streaming services",
            "3x on phone plans",
            "$200 welcome bonus after $500 spend in first 3 months",
            "No foreign transaction fees",
            "Cell phone protection",
        ],
    },
    "apple_card": {
        "id": "apple_card",
        "name": "Apple Card",
        "network": "Mastercard",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#1C1C1E",
        "earning_rates": {
            "apple_purchases": 3,
            "apple_pay": 2,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "3% at Apple & select merchants, 2% Apple Pay, 1% physical card",
        "best_for": ["Apple ecosystem users", "Apple Pay users", "privacy-conscious spenders"],
        "transfer_partners": [],
        "perks": ["No annual fee", "No fees of any kind", "Daily Cash rewards", "Titanium physical card"],
    },
    "chase_freedom_flex": {
        "id": "chase_freedom_flex",
        "name": "Chase Freedom Flex",
        "network": "Mastercard",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#1A3A6B",
        "earning_rates": {
            "rotating_quarterly": 5,
            "travel_chase_portal": 5,
            "dining": 3,
            "drugstore": 3,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "5% on rotating quarterly categories (up to $1,500/qtr), 3x dining & drugstores, 1% everything else",
        "best_for": ["category maximizers", "dining spenders", "pharmacy regulars"],
        "transfer_partners": ["Chase Ultimate Rewards"],
        "perks": [
            "No annual fee",
            "5% on rotating quarterly categories (grocery stores, gas, Amazon, etc.)",
            "3% on dining & drugstores",
            "Cell phone protection up to $800",
            "$200 welcome bonus after $500 spend in 3 months",
            "Purchase protection & extended warranty",
        ],
    },
    "amex_blue_cash_preferred": {
        "id": "amex_blue_cash_preferred",
        "name": "Amex Blue Cash Preferred",
        "network": "Amex",
        "annual_fee": 95,
        "color": "#0075C9",
        "earning_rates": {
            "groceries": 6,
            "streaming": 6,
            "transit": 3,
            "gas": 3,
            "other": 1,
        },
        "credits": [
            {
                "id": "disney_bundle",
                "name": "Disney Bundle Credit",
                "amount": 7,
                "frequency": "monthly",
                "annual_value": 84,
                "merchants": ["Disney+", "Hulu", "ESPN+"],
                "description": "$7/month statement credit on Disney Bundle subscription",
                "expires": "end_of_month",
                "how_to_use": "Pay for your Disney Bundle with your Amex Blue Cash Preferred. The $7 statement credit posts automatically each month.",
                "auto_detected": True,
                "tip": "If you already subscribe to Disney+/Hulu/ESPN+, this credit essentially makes the card free after the $95 fee.",
            },
        ],
        "total_annual_credits": 84,
        "net_value_after_fee": -11,
        "cashback_highlight": "6% at U.S. supermarkets (up to $6k/yr), 6% on select streaming, 3% on transit & gas",
        "best_for": ["grocery spenders", "families", "streaming subscribers", "transit commuters"],
        "transfer_partners": [],
        "perks": [
            "$95 annual fee ($0 intro first year)",
            "6% at U.S. supermarkets on up to $6,000/year (then 1%)",
            "6% on select U.S. streaming subscriptions",
            "3% on U.S. gas stations",
            "3% on transit (subway, buses, rideshare, taxis, parking)",
            "$84/year Disney Bundle credit",
            "Return protection & purchase protection",
            "$250 welcome bonus after $3,000 spend in 6 months",
        ],
    },
    "amex_blue_cash_everyday": {
        "id": "amex_blue_cash_everyday",
        "name": "Amex Blue Cash Everyday",
        "network": "Amex",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#0075C9",
        "earning_rates": {
            "groceries": 3,
            "online_shopping": 3,
            "gas": 3,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "3% at U.S. supermarkets, 3% on U.S. online retail, 3% on U.S. gas — no annual fee",
        "best_for": ["grocery shoppers", "online shoppers", "no-annual-fee seekers"],
        "transfer_partners": [],
        "perks": [
            "No annual fee",
            "3% at U.S. supermarkets on up to $6,000/year",
            "3% on U.S. online retail purchases",
            "3% on U.S. gas stations",
            "$200 welcome bonus after $2,000 spend in 6 months",
            "0% intro APR 15 months on purchases",
            "Car rental loss & damage insurance",
        ],
    },
    "citi_custom_cash": {
        "id": "citi_custom_cash",
        "name": "Citi Custom Cash Card",
        "network": "Mastercard",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#003A6C",
        "earning_rates": {
            "top_category_auto": 5,
            "other": 1,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "5% cash back automatically on your top eligible spend category each billing cycle (up to $500/mo), 1% on everything else",
        "best_for": ["single-category maximizers", "people with one dominant spend category", "no-annual-fee seekers"],
        "transfer_partners": ["Citi ThankYou Points"],
        "perks": [
            "No annual fee",
            "Automatically earns 5% on whichever of these you spend most on each month: restaurants, grocery stores, gas stations, select travel, select transit, streaming, drugstores, home improvement, fitness clubs, live entertainment",
            "Up to $500/month eligible for the 5% rate",
            "$200 welcome bonus after $1,500 spend in 6 months",
            "0% intro APR 15 months",
            "No foreign transaction fee",
        ],
    },
    "capital_one_quicksilver": {
        "id": "capital_one_quicksilver",
        "name": "Capital One Quicksilver",
        "network": "Visa",
        "annual_fee": 0,
        "no_annual_fee": True,
        "color": "#D03027",
        "earning_rates": {
            "travel_hotels_c1": 5,
            "travel_rental_c1": 5,
            "other": 1.5,
        },
        "credits": [],
        "total_annual_credits": 0,
        "net_value_after_fee": 0,
        "cashback_highlight": "1.5% cash back on every purchase, 5% on hotels & rental cars booked via Capital One Travel — no annual fee",
        "best_for": ["simplicity seekers", "flat-rate cashback", "light travelers"],
        "transfer_partners": [],
        "perks": [
            "No annual fee",
            "Unlimited 1.5% cash back on all purchases",
            "5% on hotels and rental cars booked through Capital One Travel",
            "$200 welcome bonus after $500 spend in 3 months",
            "No foreign transaction fees",
            "Extended warranty & travel accident insurance",
        ],
    },
    "bank_of_america_premium_rewards": {
        "id": "bank_of_america_premium_rewards",
        "name": "Bank of America Premium Rewards",
        "network": "Visa",
        "annual_fee": 95,
        "color": "#E31837",
        "earning_rates": {
            "travel": 2,
            "dining": 2,
            "other": 1.5,
        },
        "credits": [
            {
                "id": "airline_incidentals",
                "name": "Airline Incidental Fee Credit",
                "amount": 100,
                "frequency": "annual",
                "annual_value": 100,
                "merchants": ["Airlines"],
                "description": "$100/year airline incidental fee credit (baggage, seat upgrades, in-flight purchases)",
                "expires": "annual",
                "how_to_use": "Use your card for airline incidental fees — baggage, seat upgrades, in-flight food, change fees. Credit posts automatically. Does NOT cover airfare purchases.",
                "auto_detected": False,
                "tip": "Check a bag or buy a seat upgrade to easily use the $100 credit.",
            },
            {
                "id": "global_entry_bofa",
                "name": "Global Entry / TSA PreCheck Credit",
                "amount": 100,
                "frequency": "every_4_years",
                "annual_value": 25,
                "merchants": ["Global Entry", "TSA PreCheck"],
                "description": "$100 Global Entry or $85 TSA PreCheck application fee credit",
                "expires": "every_4_years",
                "how_to_use": "Pay for your Global Entry or TSA PreCheck application with this card. Credit posts within 1–2 billing cycles.",
                "auto_detected": False,
                "tip": "Global Entry includes TSA PreCheck — get both with one $100 application.",
            },
        ],
        "total_annual_credits": 125,
        "net_value_after_fee": 30,
        "cashback_highlight": "2x on travel & dining, 1.5x everything else — extra value with Preferred Rewards status (up to 2.625x on everything)",
        "best_for": ["Bank of America customers", "Preferred Rewards members", "travelers", "diners"],
        "transfer_partners": [],
        "perks": [
            "$95 annual fee",
            "2x on travel and dining",
            "1.5x on all other purchases",
            "Preferred Rewards boost: Platinum Honors members earn 2.625x on everything",
            "$100 annual airline incidental credit",
            "$100 Global Entry / TSA PreCheck credit every 4 years",
            "No foreign transaction fees",
            "$500 welcome bonus after $4,000 spend in 90 days",
        ],
    },
    "marriott_bonvoy_boundless": {
        "id": "marriott_bonvoy_boundless",
        "name": "Marriott Bonvoy Boundless",
        "network": "Visa",
        "annual_fee": 95,
        "color": "#8B1A1A",
        "earning_rates": {
            "marriott": 17,
            "groceries": 3,
            "dining": 3,
            "gas": 3,
            "other": 2,
        },
        "credits": [
            {
                "id": "free_night_award",
                "name": "Annual Free Night Award",
                "amount": 150,
                "frequency": "annual",
                "annual_value": 150,
                "merchants": ["Marriott Hotels"],
                "description": "One free night certificate each year (up to 35,000 points, worth ~$150+)",
                "expires": "annual",
                "how_to_use": "Your free night certificate is issued each card anniversary year. Redeem at Marriott.com for any property up to 35,000 points. Book early — peak dates fill up fast.",
                "auto_detected": False,
                "tip": "Use the free night at a Category 4–5 property to get maximum value (often $150–$250/night).",
            },
        ],
        "total_annual_credits": 150,
        "net_value_after_fee": 55,
        "cashback_highlight": "17x at Marriott hotels, 3x on groceries/dining/gas, annual free night worth $150+",
        "best_for": ["Marriott loyalists", "hotel collectors", "business travelers"],
        "transfer_partners": ["Marriott Bonvoy"],
        "perks": [
            "$95 annual fee",
            "17x Bonvoy points at Marriott hotels (6x card + 10x member + 1x base)",
            "3x on groceries, dining, and gas",
            "Annual free night certificate (up to 35,000 points)",
            "15 elite night credits per year (toward Silver/Gold status)",
            "No foreign transaction fees",
            "$125 welcome bonus: 3 free nights after $3,000 spend in 3 months",
        ],
    },
}


def get_all_cards():
    return list(CARD_DATABASE.values())


def get_card(card_id: str):
    return CARD_DATABASE.get(card_id)


def get_cards_context_for_ai() -> str:
    """Returns a formatted string of all card data to inject into Gemini as grounding context."""
    lines = [
        "=== CREDIT CARD BENEFIT DATABASE (Use ONLY this data. Do not use training knowledge — it may be outdated.) ===",
        "",
        "CATEGORY KEY LEGEND (do not equate categories — each is distinct):",
        "  dining          = restaurants, cafes, fast food",
        "  groceries       = supermarkets, grocery stores",
        "  transit         = subway, bus, commuter rail, ferry, tolls, parking garages, rideshare (Uber/Lyft)",
        "  travel_other    = hotels, airlines, car rentals, NOT transit/subway",
        "  travel_chase_portal = purchases via Chase Travel portal only",
        "  gas             = gas stations and EV charging",
        "  streaming       = streaming subscriptions (Netflix, Spotify, etc.)",
        "  other           = everything not listed above (default/catch-all rate)",
        "  If a category is not listed in a card's earning_rates, it earns the 'other' rate.",
        "",
    ]
    for card in CARD_DATABASE.values():
        lines.append(f"CARD: {card['name']}")
        lines.append(f"  Annual Fee: ${card['annual_fee']}")
        lines.append(f"  Total Annual Credits: ${card['total_annual_credits']}")
        lines.append(f"  Earning Rates: {card['earning_rates']}")
        lines.append(f"  Credits:")
        for credit in card["credits"]:
            lines.append(f"    - {credit['name']}: ${credit['amount']} ({credit['frequency']}) — {credit['description']}")
        lines.append(f"  Best For: {', '.join(card['best_for'])}")
        lines.append(f"  Transfer Partners: {', '.join(card.get('transfer_partners', []))}")
        lines.append("")
    return "\n".join(lines)
